- hosts: localhost
  tasks:
    - name: copy Dockerfile
      copy:
        src: /home/runner/work/githut-action-testing-repo/githut-action-testing-repo/Dockerfile
        dest: /home/runner/work/githut-action-testing-repo/githut-action-testing-repo/nodejs-app/Dockerfile
    - name: build container image
      docker_image:
        name: nodejs-app:latest
        build:
          path: ./nodejs-app
          source: build
        state: present
    - name: run container
      docker_container:
        image: nginx:stable
        name: nginx
        state: started
        auto_remove: true
        ports:
          - "49160:8080"
