- hosts: localhost
  tasks:
    - name: copy Dockerfile
      copy:
        src: /home/runner/work/githut-action-testing-repo/githut-action-testing-repo/Dockerfile
        dest: /home/runner/work/githut-action-testing-repo/githut-action-testing-repo/nodejs-app/Dockerfile
    
    - name: build container image
      docker_image:
        name: nodejs-app:latest
        source: build
        build:
          path: /home/runner/work/githut-action-testing-repo/githut-action-testing-repo/nodejs-app
        state: present
    
    - name: run container
      docker_container:
        image: nodejs-app:latest
        name: node
        state: started
        auto_remove: true
        ports:
          - "49160:8080"

    # - name: printing variables
    #   debug:
    #     msg: "The environment is {{ ENV }} with Node version {{ NODE }}"