name: Ansible Docker Action

on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the application'
        required: true
        default: 'stage'
        type: choice
        options:
        - prod
        - stage
      nodeversion:
        description: 'Select the Node version'
        required: true
        default: '14.x'
        type: choice
        options:
        - 16.x
        - 14.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js env
        uses: actions/setup-node@v2.5.2
        with:
          node-version: ${{ inputs.nodeversion }}
      - run: npm install
        working-directory: ./nodejs-app
      - run: ls -al
        working-directory: ./nodejs-app

  run-playbook:
    runs-on: ubuntu-latest
    steps:
      - name: Getting docker version
        run: docker --version

      - uses: actions/checkout@v3
      - run: |
          echo "ENV: $stage_prod" >> variables.yml
          echo "NODE: $nodev" >> variables.yml
        env:
          stage_prod: ${{ inputs.environment }}
          nodev: ${{ inputs.nodeversion}}
        
      - name: Copying the inputs to the variables.yml file
        uses: actions/upload-artifact@v3
        with:
          name: variables
          path: ansible/variables.yml

      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install dependencies Including Ansible
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi
      
      - name: Downloading artifacts
        uses: actions/download-artifact@v3
        with:
          name: variables
      -  run : ls

      - name: Running ansible playbook
        run: |
          whoami
          ansible-playbook -i inventory ansible/nodeapp-playbook.yml
      - name: Testing container
        run: curl -i localhost:49160
