name: Ansible Docker Swarm

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js env
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 16.x
      - run: npm ci
        working-directory: ./nodejs-app
      - run: npm build
        working-directory: ./nodejs-app

  run-playbook:
    runs-on: ubuntu-latest
    steps:
      - name: IP addr of the runner
        run: curl ifconfig.io
        
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies Including Ansible
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi
      - name: run playbook
        run: |
          ansible-playbook -i inventory ansible/hello-world.yaml
